/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.microsphere.spring.boot.actuate.endpoint;

import io.microsphere.spring.boot.configuration.metadata.ConfigurationMetadataReader;
import org.springframework.boot.actuate.endpoint.annotation.Endpoint;
import org.springframework.boot.actuate.endpoint.annotation.ReadOperation;
import org.springframework.boot.configurationprocessor.metadata.ConfigurationMetadata;

/**
 * {@link Endpoint @Endpoint} to expose the {@link ConfigurationMetadata Configuration Metadata} that was generated by
 * "org.springframework.boot:spring-boot-configuration-processor"
 *
 * @author <a href="mailto:mercyblitz@gmail.com">Mercy<a/>
 * @see ConfigurationMetadata
 * @since 1.0.0
 */
@Endpoint(id = "configMetadata")
public class ConfigurationMetadataEndpoint {

    private final ConfigurationMetadataReader configurationMetadataReader;

    public ConfigurationMetadataEndpoint(ClassLoader classLoader) {
        this.configurationMetadataReader = new ConfigurationMetadataReader(classLoader);
    }

    @ReadOperation
    public ConfigurationMetadata getConfigurationMetadata() {
        return this.configurationMetadataReader.read();
    }
}
