/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.microsphere.spring.boot.actuate.endpoint;

import io.microsphere.spring.boot.env.config.metadata.ConfigurationMetadataRepository;
import org.springframework.boot.actuate.endpoint.annotation.Endpoint;
import org.springframework.boot.actuate.endpoint.annotation.ReadOperation;
import org.springframework.boot.configurationprocessor.metadata.ConfigurationMetadata;
import org.springframework.boot.configurationprocessor.metadata.ItemMetadata;

import java.util.Collection;

/**
 * {@link Endpoint @Endpoint} to expose the {@link ConfigurationMetadata Configuration Metadata} that was generated by
 * "org.springframework.boot:spring-boot-configuration-processor"
 *
 * @author <a href="mailto:mercyblitz@gmail.com">Mercy<a/>
 * @see ConfigurationMetadata
 * @see ConfigurationMetadataRepository
 * @since 1.0.0
 */
@Endpoint(id = "configMetadata")
public class ConfigurationMetadataEndpoint {

    private final ConfigurationMetadataRepository configurationMetadataRepository;

    /**
     * Constructs a new {@link ConfigurationMetadataEndpoint} with the given {@link ConfigurationMetadataRepository}.
     *
     * <h3>Example Usage</h3>
     * <pre>{@code
     *   ConfigurationMetadataRepository repository = new ConfigurationMetadataRepository(reader);
     *   ConfigurationMetadataEndpoint endpoint = new ConfigurationMetadataEndpoint(repository);
     * }</pre>
     *
     * @param configurationMetadataRepository the {@link ConfigurationMetadataRepository} to use
     */
    public ConfigurationMetadataEndpoint(ConfigurationMetadataRepository configurationMetadataRepository) {
        this.configurationMetadataRepository = configurationMetadataRepository;
    }

    /**
     * Returns the {@link ConfigurationMetadataDescriptor} containing all configuration metadata
     * groups and properties.
     *
     * <h3>Example Usage</h3>
     * <pre>{@code
     *   ConfigurationMetadataEndpoint endpoint = new ConfigurationMetadataEndpoint(repository);
     *   ConfigurationMetadataDescriptor descriptor = endpoint.getConfigurationMetadata();
     * }</pre>
     *
     * @return a {@link ConfigurationMetadataDescriptor} with the aggregated metadata
     */
    @ReadOperation
    public ConfigurationMetadataDescriptor getConfigurationMetadata() {
        ConfigurationMetadataDescriptor configurationMetadata = new ConfigurationMetadataDescriptor();
        configurationMetadata.groups = this.configurationMetadataRepository.getGroups();
        configurationMetadata.properties = this.configurationMetadataRepository.getProperties();
        return configurationMetadata;
    }

    /**
     * The Descriptor class for {@link ConfigurationMetadata}
     */
    public static class ConfigurationMetadataDescriptor {

        private Collection<ItemMetadata> groups;

        private Collection<ItemMetadata> properties;

        /**
         * Returns the collection of group {@link ItemMetadata} entries.
         *
         * <h3>Example Usage</h3>
         * <pre>{@code
         *   ConfigurationMetadataDescriptor descriptor = endpoint.getConfigurationMetadata();
         *   Collection<ItemMetadata> groups = descriptor.getGroups();
         * }</pre>
         *
         * @return a {@link Collection} of group {@link ItemMetadata}
         */
        public Collection<ItemMetadata> getGroups() {
            return groups;
        }

        /**
         * Returns the collection of property {@link ItemMetadata} entries.
         *
         * <h3>Example Usage</h3>
         * <pre>{@code
         *   ConfigurationMetadataDescriptor descriptor = endpoint.getConfigurationMetadata();
         *   Collection<ItemMetadata> properties = descriptor.getProperties();
         * }</pre>
         *
         * @return a {@link Collection} of property {@link ItemMetadata}
         */
        public Collection<ItemMetadata> getProperties() {
            return properties;
        }
    }
}